# config.yaml

#########
# FREQUENTLY NEEDS TO BE CHANGED
#########

## input/output
reads_dir:  ""
outdir:     ""
suffix1: "_L001_R1_001.fastq.gz"
suffix2: "_L001_R2_001.fastq.gz"
remove_sample_index: True
keep_trimmed_reads: False
wastewater_mode: False

#########
# SOMETIMES NEEDS TO BE CHANGED
#########

## analysis parameters
min_depth:  10
consensus_threshold : 0.5
snp_threshold : 0.03
indel_threshold : 0.03
mixed_threshold : 0.1

#########
# SHOULD NOT NEED TO BE CHANGED
#########

## reference and database files
# note: these will be downloaded automatically if not present
nextclade_name:
  RSVA: "rsv_a"
  RSVB: "rsv_b"
nextclade_dataset:
  RSVA: "data/rsv_a"
  RSVB: "data/rsv_b"
# note: these will be present in the nextclade download
#    Can still be changed to custom references, but you will need to
#        ensure that you have created appropriate bed files for primers.
refs:
  RSVA: "data/prototype_references/NC_038235.1.fasta"
  RSVB: "data/prototype_references/NC_001781.1.fasta"
  # RSVA: "data/rsv_a/reference.fasta"
  # RSVB: "data/rsv_b/reference.fasta"
primers_bed: 
  RSVA:  "data/RSVA_prototype.mapped.bed"
  RSVB:  "data/RSVB_prototype.mapped.bed"
  # RSVA:  "data/RSVA.primer.bed"
  # RSVB:  "sandbox/RSVB.primer.bed"
annotations: 
  RSVA:  "data/prototype_references/NC_038235.1.gff3"
  RSVB:  "data/prototype_references/NC_001781.1.gff3"
  # RSVA: "data/RSVA_nextclade.gff3"
  # RSVB: "data/RSVB_nextclade.gff3"

# note: pre-built based on the nextclade references
#    Can still be changed to custom databases, but you will need to
#        ensure that you have created appropriate syldb files
syldb:   "data/rsv_database.syldb"
