name: rsv_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12.3 
  - fastp=0.23.4
  - bwa=0.7.19
  - samtools=1.21
  - bcftools=1.21
  - lofreq=2.1.5
  - bedtools=2.31.1
  - snakemake=9.5.1
  - sylph=0.8.1